server:
  port: 8111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  type-aliases-package: com.travel.entity #对应实体类

